name: Node.js CI

on:
  push:
    branches:
      - feature/methni-sourour/add-docker-build-push-step-to-ci  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Change this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image 
      run: docker build -t sourour-image:v1 .

    - name: Login 
      run:  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image 
      run:  docker push sourour-image:v1

        
        
        

